version: "3.8"

services:
    postgres:
        image: postgres:14.4
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: phaslo
            POSTGRES_USER: puser
            POSTGRES_DB: pbaza
    
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: phaslo

    rabbitmq:
        image: rabbitmq:latest
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        
